# presents verb 50
# INSERT INTO tests (question, correct_answer, options, test_type, theme_id) VALUES
test_presens_question = [
    ('Hva er presens av verbet "å være"?', 'er', 'er, var, vært', 'presens', 1),
    ('Hva er presens av verbet "å spise"?', 'spiser', 'spiste, spiser, har spist', 'presens', 1),
    ('Hva er presens av verbet "å gå"?', 'går', 'går, gikk, har gått', 'presens', 1),
    ('Hva er presens av verbet "å lese"?', 'leser', 'leste, leser, har lest', 'presens', 1),
    ('Hva er presens av verbet "å skrive"?', 'skriver', 'skrev, skriver, har skrevet', 'presens', 1),
    ('Hva er presens av verbet "å kjøpe"?', 'kjøper', 'kjøpte, kjøper, har kjøpt', 'presens', 1),
    ('Hva er presens av verbet "å lage"?', 'lager', 'laget, lager, har laget', 'presens', 1),
    ('Hva er presens av verbet "å se"?', 'ser', 'så, ser, har sett', 'presens', 1),
    ('Hva er presens av verbet "å dra"?', 'drar', 'dro, drar, har dratt', 'presens', 1),
    ('Hva er presens av verbet "å forstå"?', 'forstår', 'forsto, forstår, har forstått', 'presens', 1),
    ('Hva er presens av verbet "å hjelpe"?', 'hjelper', 'hjalp, hjelper, har hjulpet', 'presens', 1),
    ('Hva er presens av verbet "å finne"?', 'finner', 'fant, finner, har funnet', 'presens', 1),
    ('Hva er presens av verbet "å begynne"?', 'begynner', 'begynte, begynner, har begynt', 'presens', 1),
    ('Hva er presens av verbet "å elske"?', 'elsker', 'elsket, elsker, har elsket', 'presens', 1),
    ('Hva er presens av verbet "å tro"?', 'tror', 'tro, tror, har trodd', 'presens', 1),
    ('Hva er presens av verbet "å huske"?', 'husker', 'husket, husker, har husket', 'presens', 1),
    ('Hva er presens av verbet "å vaske"?', 'vasker', 'vasket, vasker, har vasket', 'presens', 1),
    ('Hva er presens av verbet "å danse"?', 'danser', 'dannet, danser, har danset', 'presens', 1),
    ('Hva er presens av verbet "å le"?', 'ler', 'lo, ler, har ledd', 'presens', 1),
    ('Hva er presens av verbet "å sove"?', 'sover', 'sov, sover, har sovet', 'presens', 1),
    ('Hva er presens av verbet "å skrive"?', 'skriver', 'skrev, skriver, har skrevet', 'presens', 1),
    ('Hva er presens av verbet "å kaste"?', 'kaster', 'kastet, kaster, har kastet', 'presens', 1),
    ('Hva er presens av verbet "å bruke"?', 'bruker', 'brukte, bruker, har brukt', 'presens', 1),
    ('Hva er presens av verbet "å åpne"?', 'åpner', 'åpnet, åpner, har åpnet', 'presens', 1),
    ('Hva er presens av verbet "å møte"?', 'møter', 'møtte, møter, har møtt', 'presens', 1),
    ('Hva er presens av verbet "å ta"?', 'tar', 'tok, tar, har tatt', 'presens', 1),
    ('Hva er presens av verbet "å høre"?', 'hører', 'hørte, hører, har hørt', 'presens', 1),
    ('Hva er presens av verbet "å spise"?', 'spiser', 'spiste, spiser, har spist', 'presens', 1),
    ('Hva er presens av verbet "å tenke"?', 'tenker', 'tenkte, tenker, har tenkt', 'presens', 1),
    ('Hva er presens av verbet "å bruke"?', 'bruker', 'brukte, bruker, har brukt', 'presens', 1),
    ('Hva er presens av verbet "å ringe"?', 'ringer', 'ringte, ringer, har ringt', 'presens', 1),
    ('Hva er presens av verbet "å kjøpe"?', 'kjøper', 'kjøpte, kjøper, har kjøpt', 'presens', 1),
    ('Hva er presens av verbet "å vente"?', 'venter', 'ventet, venter, har ventet', 'presens', 1),
    ('Hva er presens av verbet "å bygge"?', 'bygger', 'bygde, bygger, har bygd', 'presens', 1),
    ('Hva er presens av verbet "å skrive"?', 'skriver', 'skrev, skriver, har skrevet', 'presens', 1),
    ('Hva er presens av verbet "å leke"?', 'leker', 'lekte, leker, har lekt', 'presens', 1),
    ('Hva er presens av verbet "å tegne"?', 'tegner', 'tegnte, tegner, har tegnet', 'presens', 1),
    ('Hva er presens av verbet "å spørre"?', 'spør', 'spurte, spør, har spurt', 'presens', 1),
    ('Hva er presens av verbet "å finne"?', 'finner', 'fant, finner, har funnet', 'presens', 1),
    ('Hva er presens av verbet "å trene"?', 'trener', 'trente, trener, har trent', 'presens', 1),
    ('Hva er presens av verbet "å svare"?', 'svarer', 'svarte, svarer, har svart', 'presens', 1),
    ('Hva er presens av verbet "å høre"?', 'hører', 'hørte, hører, har hørt', 'presens', 1),
    ('Hva er presens av verbet "å synge"?', 'synger', 'sang, synger, har sunget', 'presens', 1),
    ('Hva er presens av verbet "å kjøpe"?', 'kjøper', 'kjøpte, kjøper, har kjøpt', 'presens', 1),
    ('Hva er presens av verbet "å tro"?', 'tror', 'tro, tror, har trodd', 'presens', 1),
    ('Hva er presens av verbet "å bruke"?', 'bruker', 'brukte, bruker, har brukt', 'presens', 1),
    ('Hva er presens av verbet "å fly"?', 'flyr', 'fløy, flyr, har fløyet', 'presens', 1),
    ('Hva er presens av verbet "å rydde"?', 'rydder', 'rydde, ryddet, har ryddet', 'presens', 1),
    ('Hva er presens av verbet "å møte"?', 'møter', 'møtte, møter, har møtt', 'presens', 1),
    ('Hva er presens av verbet "å begynne"?', 'begynner', 'begynte, begynner, har begynt', 'presens', 1),
    ('Hva er presens av verbet "å gå"?', 'går', 'gikk, går, har gått', 'presens', 1),
    ('Hva er presens av verbet "å selge"?', 'selger', 'solgte, selger, har solgt', 'presens', 1),
    ('Hva er presens av verbet "å dra"?', 'drar', 'dro, drar, har dratt', 'presens', 1)
]
# 50 preteritum
# INSERT INTO tests (question, correct_answer, options, test_type, theme_id) VALUES
test_preteritum_question = [
    ('Hva er preteritum av verbet "å være"?', 'var', 'var, er, vært', 'preteritum', 1),
    ('Hva er preteritum av verbet "å spise"?', 'spiste', 'spiste, spiser, har spist', 'preteritum', 1),
    ('Hva er preteritum av verbet "å gå"?', 'gikk', 'gikk, går, har gått', 'preteritum', 1),
    ('Hva er preteritum av verbet "å lese"?', 'leste', 'leste, leser, har lest', 'preteritum', 1),
    ('Hva er preteritum av verbet "å skrive"?', 'skrev', 'skrev, skriver, har skrevet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å kjøpe"?', 'kjøpte', 'kjøpte, kjøper, har kjøpt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å lage"?', 'lagde', 'lagde, lager, har laget', 'preteritum', 1),
    ('Hva er preteritum av verbet "å se"?', 'så', 'så, ser, har sett', 'preteritum', 1),
    ('Hva er preteritum av verbet "å dra"?', 'dro', 'dro, drar, har dratt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å forstå"?', 'forsto', 'forsto, forstår, har forstått', 'preteritum', 1),
    ('Hva er preteritum av verbet "å hjelpe"?', 'hjalp', 'hjalp, hjelper, har hjulpet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å finne"?', 'fant', 'fant, finner, har funnet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å begynne"?', 'begynte', 'begynte, begynner, har begynt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å elske"?', 'elsket', 'elsket, elsker, har elsket', 'preteritum', 1),
    ('Hva er preteritum av verbet "å tro"?', 'trodde', 'trodde, tror, har trodd', 'preteritum', 1),
    ('Hva er preteritum av verbet "å huske"?', 'husket', 'husket, husker, har husket', 'preteritum', 1),
    ('Hva er preteritum av verbet "å vaske"?', 'vasket', 'vasket, vasker, har vasket', 'preteritum', 1),
    ('Hva er preteritum av verbet "å danse"?', 'danset', 'danset, danser, har danset', 'preteritum', 1),
    ('Hva er preteritum av verbet "å le"?', 'lo', 'lo, ler, har ledd', 'preteritum', 1),
    ('Hva er preteritum av verbet "å sove"?', 'sov', 'sov, sover, har sovet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å skrive"?', 'skrev', 'skrev, skriver, har skrevet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å kaste"?', 'kastet', 'kastet, kaster, har kastet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å bruke"?', 'brukte', 'brukte, bruker, har brukt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å åpne"?', 'åpnet', 'åpnet, åpner, har åpnet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å møte"?', 'møtte', 'møtte, møter, har møtt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å ta"?', 'tok', 'tok, tar, har tatt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å høre"?', 'hørte', 'hørte, hører, har hørt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å spise"?', 'spiste', 'spiste, spiser, har spist', 'preteritum', 1),
    ('Hva er preteritum av verbet "å tenke"?', 'tenkte', 'tenkte, tenker, har tenkt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å bruke"?', 'brukte', 'brukte, bruker, har brukt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å ringe"?', 'ringte', 'ringte, ringer, har ringt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å kjøpe"?', 'kjøpte', 'kjøpte, kjøper, har kjøpt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å vente"?', 'ventet', 'ventet, venter, har ventet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å bygge"?', 'bygde', 'bygde, bygger, har bygd', 'preteritum', 1),
    ('Hva er preteritum av verbet "å skrive"?', 'skrev', 'skrev, skriver, har skrevet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å leke"?', 'lekte', 'lekte, leker, har lekt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å tegne"?', 'tegnet', 'tegnet, tegner, har tegnet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å spørre"?', 'spurte', 'spurte, spør, har spurt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å finne"?', 'fant', 'fant, finner, har funnet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å trene"?', 'trente', 'trente, trener, har trent', 'preteritum', 1),
    ('Hva er preteritum av verbet "å svare"?', 'svarte', 'svarte, svarer, har svart', 'preteritum', 1),
    ('Hva er preteritum av verbet "å høre"?', 'hørte', 'hørte, hører, har hørt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å synge"?', 'sang', 'sang, synger, har sunget', 'preteritum', 1),
    ('Hva er preteritum av verbet "å kjøpe"?', 'kjøpte', 'kjøpte, kjøper, har kjøpt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å tro"?', 'trodde', 'trodde, tror, har trodd', 'preteritum', 1),
    ('Hva er preteritum av verbet "å bruke"?', 'brukte', 'brukte, bruker, har brukt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å fly"?', 'fløy', 'fløy, flyr, har fløyet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å rydde"?', 'ryddet', 'ryddet, rydder, har ryddet', 'preteritum', 1),
    ('Hva er preteritum av verbet "å møte"?', 'møtte', 'møtte, møter, har møtt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å begynne"?', 'begynte', 'begynte, begynner, har begynt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å gå"?', 'gikk', 'gikk, går, har gått', 'preteritum', 1),
    ('Hva er preteritum av verbet "å selge"?', 'solgte', 'solgte, selger, har solgt', 'preteritum', 1),
    ('Hva er preteritum av verbet "å dra"?', 'dro', 'dro, drar, har dratt', 'preteritum', 1)
]
# verb forms simpl
test_simple_verb_forms = {
    "å bli": ["å bli", "blir", "ble/blei", "har blitt", "bli!"],
    "å spise": ["å spise", "spiser", "spiste", "har spist", "spis!"],
    "å skrive": ["å skrive", "skriver", "skrev", "har skrevet", "skriv!"],
    "å be": ["å be", "ber", "ba", "har bedt", "be!"],
    "å gjøre": ["å gjøre", "gjør", "gjorde", "har gjort", "gjør!"],
    "å se": ["å se", "ser", "så", "har sett", "se!"],
    "å komme": ["å komme", "kommer", "kom", "har kommet", "kom!"],
    "å gå": ["å gå", "går", "gikk", "har gått", "gå!"],
    "å ta": ["å ta", "tar", "tok", "har tatt", "ta!"],
    "å drikke": ["å drikke", "drikker", "drakk", "har drukket", "drikk!"],
    "å sove": ["å sove", "sover", "sov", "har sovet", "sov!"],
    "å høre": ["å høre", "hører", "hørte", "har hørt", "hør!"],
    "å si": ["å si", "sier", "sa", "har sagt", "si!"],
    "å vite": ["å vite", "vet", "visste", "har visst", "vit!"],
    "å vente": ["å vente", "venter", "ventet", "har ventet", "vent!"],
    "å selge": ["å selge", "selger", "solgte", "har solgt", "selg!"],
    "å lese": ["å lese", "leser", "leste", "har lest", "les!"],
    "å betale": ["å betale", "betaler", "betalte", "har betalt", "betal!"],
    "å lære": ["å lære", "lærer", "lærte", "har lært", "lær!"],
    "å jobbe": ["å jobbe", "jobber", "jobbet", "har jobbet", "jobb!"],
    "å tenke": ["å tenke", "tenker", "tenkte", "har tenkt", "tenk!"],
    "å forstå": ["å forstå", "forstår", "forsto", "har forstått", "forstå!"],
    "å møte": ["å møte", "møter", "møtte", "har møtt", "møt!"],
    "å begynne": ["å begynne", "begynner", "begynte", "har begynt", "begynn!"],
    "å bo": ["å bo", "bor", "bodde", "har bodd", "bo!"],
    "å tro": ["å tro", "tror", "trodde", "har trodd", "tro!"],
    "å spørre": ["å spørre", "spør", "spurte", "har spurt", "spør!"],
    "å forstå": ["å forstå", "forstår", "forsto", "har forstått", "forstå!"],
    "å ringe": ["å ringe", "ringer", "ringte", "har ringt", "ring!"],
    "å hjelpe": ["å hjelpe", "hjelper", "hjalp", "har hjulpet", "hjelp!"],
    "å kjøpe": ["å kjøpe", "kjøper", "kjøpte", "har kjøpt", "kjøp!"],
    "å elske": ["å elske", "elsker", "elsket", "har elsket", "elsk!"],
    "å finne": ["å finne", "finner", "fant", "har funnet", "finn!"],
    "å fly": ["å fly", "flyr", "fløy", "har fløyet", "fly!"],
    "å lære": ["å lære", "lærer", "lærte", "har lært", "lær!"],
    "å vente": ["å vente", "venter", "ventet", "har ventet", "vent!"],
    "å bli": ["å bli", "blir", "ble", "har blitt", "bli!"],
    "å se": ["å se", "ser", "så", "har sett", "se!"],
    "å skrive": ["å skrive", "skriver", "skrev", "har skrevet", "skriv!"],
    "å høre": ["å høre", "hører", "hørte", "har hørt", "hør!"],
    "å spørre": ["å spørre", "spør", "spurte", "har spurt", "spør!"],
    "å si": ["å si", "sier", "sa", "har sagt", "si!"],
    "å sove": ["å sove", "sover", "sov", "har sovet", "sov!"],
    "å dra": ["å dra", "drar", "dro", "har dratt", "dra!"],
    "å få": ["å få", "får", "fikk", "har fått", "få!"],
    "å vinne": ["å vinne", "vinner", "vant", "har vunnet", "vinn!"],
    "å le": ["å le", "ler", "lo", "har ledd", "le!"],
    "å lese": ["å lese", "leser", "leste", "har lest", "les!"],
    "å vaske": ["å vaske", "vasker", "vasket", "har vasket", "vask!"],
    "å løpe": ["å løpe", "løper", "løp", "har løpt", "løp!"],
    "å bruke": ["å bruke", "bruker", "brukte", "har brukt", "bruk!"],
    "å falle": ["å falle", "faller", "falt", "har falt", "fall!"],
    "å kaste": ["å kaste", "kaster", "kastet", "har kastet", "kast!"],
    "å sette": ["å sette", "setter", "satte", "har satt", "sett!"],
    "å like": ["å like", "liker", "likte", "har likt", "lik!"],
    "å starte": ["å starte", "starter", "startet", "har startet", "start!"],
    "å møte": ["å møte", "møter", "møtte", "har møtt", "møt!"],
    "å gråte": ["å gråte", "gråter", "gråt", "har grått", "gråt!"],
    "å danse": ["å danse", "danser", "danset", "har danset", "dans!"],
    "å synge": ["å synge", "synger", "sang", "har sunget", "syng!"],
    "å tenke": ["å tenke", "tenker", "tenkte", "har tenkt", "tenk!"],
    "å lukke": ["å lukke", "lukker", "lukket", "har lukket", "lukk!"],
    "å dra": ["å dra", "drar", "dro", "har dratt", "dra!"],
    "å svømme": ["å svømme", "svømmer", "svømte", "har svømt", "svøm!"],
    "å lære": ["å lære", "lærer", "lærte", "har lært", "lær!"],
    "å vente": ["å vente", "venter", "ventet", "har ventet", "vent!"],
    "å lage": ["å lage", "lager", "laget", "har laget", "lag!"],
    "å leie": ["å leie", "leier", "leide", "har leid", "lei!"],
    "å passe": ["å passe", "passer", "passet", "har passet", "pass!"],
    "å svare": ["å svare", "svarer", "svarte", "har svart", "svar!"],
    "å danse": ["å danse", "danser", "danset", "har danset", "dans!"],
    "å selge": ["å selge", "selger", "solgte", "har solgt", "selg!"],
    "å lese": ["å lese", "leser", "leste", "har lest", "les!"],
    "å gi": ["å gi", "gir", "gav", "har gitt", "gi!"],
    "å rydde": ["å rydde", "rydder", "ryddet", "har ryddet", "rydd!"],
    "å smake": ["å smake", "smaker", "smakte", "har smakt", "smak!"],
    "å telle": ["å telle", "teller", "talte", "har talt", "tell!"],
    "å kjøpe": ["å kjøpe", "kjøper", "kjøpte", "har kjøpt", "kjøp!"],
    "å hente": ["å hente", "henter", "hentet", "har hentet", "hent!"],
    "å hoppe": ["å hoppe", "hopper", "hoppet", "har hoppet", "hopp!"],
    "å forstå": ["å forstå", "forstår", "forsto", "har forstått", "forstå!"],
    "å miste": ["å miste", "mister", "mistet", "har mistet", "mist!"],
    "å åpne": ["å åpne", "åpner", "åpnet", "har åpnet", "åpne!"],
    "å drømme": ["å drømme", "drømmer", "drømte", "har drømt", "drøm!"],
    "å besøke": ["å besøke", "besøker", "besøkte", "har besøkt", "besøk!"],
    "å svare": ["å svare", "svarer", "svarte", "har svart", "svar!"],
    "å møte": ["å møte", "møter", "møtte", "har møtt", "møt!"],
    "å elske": ["å elske", "elsker", "elsket", "har elsket", "elsk!"],
    "å bruke": ["å bruke", "bruker", "brukte", "har brukt", "bruk!"],
    "å leie": ["å leie", "leier", "leide", "har leid", "lei!"],
    "å velge": ["å velge", "velger", "valgte", "har valgt", "velg!"],
    "å hate": ["å hate", "hater", "hatet", "har hatet", "hat!"],
    "å stå": ["å stå", "står", "stod", "har stått", "stå!"],}
    

